import pg from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { createRequire } from "node:module";

// NOTE: PrismaClient is generated by `pnpm --filter @cyclops/db run db:generate`
// Until db:generate is run, imports from ./generated/index.js do not exist.
// createRequire is used to load the generated client at runtime in ESM context.
// After running db:generate, replace `any` types with the generated PrismaClient type.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let client: any | undefined;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getDb(): any {
  if (!client) {
    const pool = new pg.Pool({
      connectionString: process.env["DATABASE_URL"],
    });
    const adapter = new PrismaPg(pool);
    // Use createRequire for ESM-compatible require() — generated client loaded at runtime.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const _require = createRequire(import.meta.url);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { PrismaClient } = _require("./generated/index.js") as any;
    client = new PrismaClient({ adapter });
  }
  return client;
}
